---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ShinyGeode

<!-- badges: start -->
<!-- badges: end -->

ShinyGeode is an interactive and user-friendly interface for the **geode** package. Via this interface, all of the spatial mapping and analysis functions of geode are available through point-and-click, drop-down menus, check-boxes and sliders. No R scripting is needed.

The purpose of ShinyGeode is to provide a low barrier interface that benefits a wide range of users.  It allows rapid interaction with spatial data for identifying patterns, generating hypotheses, and informing further investigation and analysis.



## Installation

In R, you can install ShinyGeode directly from the CPAC [GitHub](https://github.com/cpacc/) with:

``` r
install.packages("remotes")
remotes::install_github("cpacc/ShinyGeode")
```

## Getting started

All requirements and instructions for getting started can be found in the ShinyGeode User Manual. A PDF version of the manual can be found at



An HTML version of the manual is also provided at



The HTML version is contained in a zip folder. Download and unzip (using 7-zip, as above), and then click on the manual shortcut ‘users_manual_HTML’.

